import LeanOS.ElfAdmission

/-!
# Build-time admission of one subject ELF (issue #492)

Host-only executable.  It reads one file and runs `LeanOS.ElfAdmission.admit`
over its bytes:

    leanos-elf-admit admit FILE
    leanos-elf-admit place FILE START STOP RESERVATION_START RESERVATION_STOP

`admit` prints the admitted plan (the file's size and entry point, then one
row per load segment) or `rejected<TAB><reason>` and exits 1.  `place`
additionally binds the plan to the image range `[START, STOP)` inside the
embedded-user reservation (`LeanOS.ElfAdmission.place`) and prints each
segment's physical source.  Addresses are decimal on input and hexadecimal on
output.  The build compares the plan of the standalone ELF with the plan of
the bytes read back from the linked kernel image.
-/
namespace LeanOS.ElfAdmissionGenerator

open LeanOS.ElfAdmission

def hex (value : Nat) : String := "0x" ++ String.ofList (Nat.toDigits 16 value)

def perms (segment : Segment) : String :=
  (if segment.readable then "r" else "-") ++ (if segment.writable then "w" else "-") ++
    (if segment.executable then "x" else "-")

def planRows (plan : Plan) : List String :=
  s!"elf\tfile-bytes={hex plan.fileBytes}\tentry={hex plan.entry}" ::
    (plan.segments.zipIdx.map fun (segment, index) =>
      s!"segment\t{index}\tvaddr={hex segment.vaddr}\tmem-bytes={hex segment.memBytes}" ++
        s!"\tfile-offset={hex segment.fileOffset}\tfile-bytes={hex segment.fileBytes}" ++
        s!"\tperms={perms segment}")

def placedRows (placement : Placement) (placed : List PlacedSegment) : List String :=
  (s!"placement\tstart={hex placement.start}\tstop={hex placement.stop}" ++
      s!"\treservation-start={hex placement.reservationStart}" ++
      s!"\treservation-stop={hex placement.reservationStop}") ::
    (placed.zipIdx.map fun (entry, index) =>
      s!"source\t{index}\tphysical={hex entry.source}\tbytes={hex entry.segment.fileBytes}")

def header : String :=
  "# Generated by the accepted LeanOS.ElfAdmission plan; do not edit."

def emit (rows : List String) : IO UInt32 := do
  IO.println header
  for row in rows do IO.println row
  pure 0

def reject (reason : String) : IO UInt32 := do
  IO.println s!"rejected\t{reason}"
  pure 1

def parseNat (value : String) : Except String Nat :=
  match value.toNat? with
  | some parsed => .ok parsed
  | none => .error s!"invalid decimal address: {value}"

def run : List String → IO UInt32
  | ["admit", path] => do
    match admit (← IO.FS.readBinFile path) with
    | .error reason => reject reason.name
    | .ok plan => emit (planRows plan)
  | ["place", path, start, stop, reservationStart, reservationStop] => do
    let placement? : Except String Placement := do
      pure { start := ← parseNat start, stop := ← parseNat stop,
             reservationStart := ← parseNat reservationStart,
             reservationStop := ← parseNat reservationStop }
    match placement? with
    | .error message =>
      IO.eprintln s!"error: {message}"
      pure 2
    | .ok placement =>
      match admit (← IO.FS.readBinFile path) with
      | .error reason => reject reason.name
      | .ok plan =>
        match place placement plan with
        | .error reason => reject reason.name
        | .ok placed => emit (planRows plan ++ placedRows placement placed)
  | _ => do
    IO.eprintln "usage: leanos-elf-admit admit FILE"
    IO.eprintln "       leanos-elf-admit place FILE START STOP RESERVATION_START RESERVATION_STOP"
    pure 2

end LeanOS.ElfAdmissionGenerator

def main (args : List String) : IO UInt32 :=
  LeanOS.ElfAdmissionGenerator.run args
