import LeanOS.VTdBootPlan

/-!
# Linked VT-d boot-plan generator

This host-only executable receives the final-ELF remapping-table symbol
addresses plus the CPU page-table layout, constructs the same finite
`VTdBootPlan.Input` those symbols represent over the accepted deny-all
device-domain state, requires `VTdBootPlan.compile` to accept it, and emits the
canonical root/context table words and pinned register constants consumed by
the guest constructor.  The linker, symbol extraction, generated header,
C/assembly table writes, VT-d MMIO programming, and hardware page walk remain
trusted build and integration boundaries rather than proved refinement steps.
-/
namespace LeanOS.VTdBootPlanGenerator

open LeanOS
open LeanOS.X86PageTable (pageBytes)
open LeanOS.VTdBootPlan

structure Layout where
  rootTableStart : Nat
  contextTableStart : Nat
  remappingTableEnd : Nat
  cpuRootA : Nat
  cpuTableEnd : Nat
  deriving Repr

def expectedArgumentCount : Nat := 5

def parseNat (value : String) : Except String Nat :=
  match value.toNat? with
  | some parsed => .ok parsed
  | none => .error s!"invalid decimal address: {value}"

def parseLayout (args : List String) : Except String Layout := do
  if args.length != expectedArgumentCount then
    throw s!"expected {expectedArgumentCount} decimal addresses, got {args.length}"
  let values ← args.mapM parseNat
  let valueAt (index : Nat) := values[index]?.getD 0
  pure {
    rootTableStart := valueAt 0, contextTableStart := valueAt 1,
    remappingTableEnd := valueAt 2, cpuRootA := valueAt 3, cpuTableEnd := valueAt 4 }

def frameOf (address : Nat) : Nat := address / pageBytes

/-- The linked CPU page-table frames the remapping tables must avoid.  The
range `[cpuRootA, cpuTableEnd)` is the same 22-frame block the boot page-table
plan reserves as `.pageTables`. -/
def cpuTableFrames (layout : Layout) : List Nat :=
  (List.range ((layout.cpuTableEnd - layout.cpuRootA) / pageBytes)).map
    (frameOf layout.cpuRootA + ·)

/-- The remapping-table reservation overlaid on a single usable window,
mirroring the boot page-plan generator's construction so the same authority
excludes both table families from allocation.  The seven non-`pageTables`
identities occupy the fixed low frames below the linked remapping block; the
`.pageTables` reservation covers the whole `[rootTableStart, remappingTableEnd)`
span, which contains both VT-d table frames. -/
def reservationResult (layout : Layout) : Option BootReservation.Result :=
  let imageEnd := layout.remappingTableEnd
  let handoff := BootMemoryMap.mkHandoff [{ base := 0, length := imageEnd, kind := .usable }]
  let manifest : List BootReservation.Reservation :=
    [{ identity := .lowMemory, start := 0, length := pageBytes, lifetime := .permanent },
     { identity := .loadedImage, start := pageBytes,
       length := imageEnd - pageBytes, lifetime := .permanent },
     { identity := .descriptorTables, start := pageBytes,
       length := pageBytes, lifetime := .permanent },
     { identity := .kernelStacks, start := 2 * pageBytes,
       length := pageBytes, lifetime := .permanent },
     { identity := .embeddedUsers, start := 3 * pageBytes,
       length := pageBytes, lifetime := .permanent },
     { identity := .ordinaryEntryGuard, start := 6 * pageBytes,
       length := pageBytes, lifetime := .permanent },
     { identity := .ordinaryEntryStack, start := 7 * pageBytes,
       length := pageBytes, lifetime := .permanent },
     { identity := .pageTables, start := layout.rootTableStart,
       length := imageEnd - layout.rootTableStart, lifetime := .permanent },
     { identity := .multibootInfo, start := pageBytes, length := pageBytes,
       lifetime := .bootstrap }]
  (BootReservation.initializeAllocator handoff manifest).toOption

def input (layout : Layout) : Input :=
  { state := IOMMU.emptyState
    rootTableFrame := frameOf layout.rootTableStart
    contextTableFrame := frameOf layout.contextTableStart
    cpuTableFrames := cpuTableFrames layout
    reservationResult := reservationResult layout }

def emitArray (name : String) (entries : List Nat) : String :=
  let body := String.intercalate ",\n" (entries.map fun entry => s!"  {entry}ULL")
  "static const unsigned long long " ++ name ++ "[" ++ toString entries.length ++ "] = {\n" ++
    body ++ "\n};"

def emitConstant (name : String) (value : Nat) : String :=
  "#define " ++ name ++ " " ++ toString value ++ "ULL"

def emit (layout : Layout) : Except String String := do
  match compile (input layout) with
  | .error error => throw s!"canonical linked VT-d plan rejected: {repr error}"
  | .ok plan =>
    pure <| String.intercalate "\n"
      ["/* Generated by the accepted LeanOS.VTdBootPlan; do not edit. */",
       emitConstant "LEANOS_VTD_MMIO_BASE" mmioBase,
       emitConstant "LEANOS_VTD_PLAN_VERSION" planVersion.toNat,
       emitConstant "LEANOS_VTD_EXPECTED_VERSION" expectedVersionRegister.toNat,
       emitConstant "LEANOS_VTD_EXPECTED_CAP" expectedCapabilityRegister.toNat,
       emitConstant "LEANOS_VTD_EXPECTED_ECAP" expectedExtendedCapabilityRegister.toNat,
       emitConstant "LEANOS_VTD_ENABLED_GSTS" enabledGlobalStatus.toNat,
       emitConstant "LEANOS_VTD_TOPOLOGY" DMAQuarantine.q35TopologyVersion.toNat,
       emitConstant "LEANOS_VTD_ROOT_TABLE_FRAME" plan.rootFrame,
       emitConstant "LEANOS_VTD_CONTEXT_TABLE_FRAME" plan.contextFrame,
       emitConstant "LEANOS_VTD_ROOT_TABLE_ADDRESS" (plan.rootFrame * pageBytes),
       emitConstant "LEANOS_VTD_CANONICAL_JOURNAL" canonicalJournalWord,
       emitArray "leanos_vtd_root_table" (rootTableWords plan),
       emitArray "leanos_vtd_context_table" (contextTableWords plan)] ++ "\n"

end LeanOS.VTdBootPlanGenerator

def main (args : List String) : IO UInt32 := do
  match LeanOS.VTdBootPlanGenerator.parseLayout args >>=
      LeanOS.VTdBootPlanGenerator.emit with
  | .ok output =>
      IO.print output
      pure 0
  | .error message =>
      IO.eprintln s!"error: {message}"
      pure 1
