name = "leanos"
version = "0.1.0"
defaultTargets = ["LeanOS"]

[[lean_lib]]
name = "LeanOS"
moreLeanArgs = ["-DwarningAsError=true"]

[[lean_exe]]
name = "leanos-oracle"
root = "LeanOS.Oracle"

[[lean_exe]]
name = "leanos-dma-corpus"
root = "LeanOS.DMAQuarantineCorpus"
moreLeanArgs = ["-DwarningAsError=true"]

[[lean_exe]]
name = "leanos-boot-plan"
root = "LeanOS.BootPageTablePlanGenerator"
moreLeanArgs = ["-DwarningAsError=true"]
