#!/usr/bin/env bash
set -euo pipefail
[[ "${1:-}" == --version ]] && { echo "QEMU fixture version 1"; exit 0; }
log=""; for arg in "$@"; do [[ "$arg" == file:* ]] && log="${arg#file:}"; done
[[ -n "$log" ]] || exit 2
memory_mib=128
for ((i=1; i<=$#; ++i)); do
  if [[ "${!i}" == -m ]]; then next=$((i + 1)); memory_mib="${!next%M}"; fi
done
case "${LEANOS_QEMU_FIXTURE_MODE:-success}" in
success) echo 'LEANOS/6 BOOT target=x86_64-q35 subjects=2 schedule=one-shot-pit controls=wp,smep,smap' > "$log"; printf '%s\n' 'LEANOS/8 PAGING root=A selected=1 leaves=4096 policy=manifest result=PASS' 'LEANOS/8 PAGING root=B selected=0 leaves=4096 policy=manifest result=PASS' 'LEANOS/8 PAGING fixture=flip-present root=A page=0 result=REJECTED' 'LEANOS/7 HANDOFF magic=valid info-bytes=1024 mmap-entries=8 result=PASS' "LEANOS/7 MAP boot-pages=4096 reported-top-mib=$((memory_mib - 1)) precedence=reserved result=PASS" 'LEANOS/7 ALLOC frame=512 firmware-usable=1 boot-accessible=1 reserved=0 result=PASS' 'LEANOS/7 SCRUB bytes=4096 zero=1 result=PASS' 'LEANOS/7 PUBLISH object=1 owner=1 stale-object=denied result=PASS' 'LEANOS/7 BOOTALLOC status=PASS' >> "$log"; awk -F '\t' '$1 ~ /^[0-9]+$/ { print "LEANOS/3 ORACLE id=" $2 " result=PASS" }' "$LEANOS_ORACLE_CORPUS" >> "$log"; printf '%s\n' 'LEANOS/6 CONTROL cr0.wp=1 cr4.smep=1 cr4.smap=1 ac=0 stage=exception-path-ready' 'LEANOS/4 PROBE kind=wp vector=14 error=3 origin=kernel address=kernel-text policy=fatal result=PASS' 'LEANOS/4 PROBE kind=smep vector=14 error=17 origin=kernel address=user-a-text policy=fatal result=PASS' 'LEANOS/6 PROBE kind=smap-direct vector=14 origin=kernel ac=0 result=PASS' 'LEANOS/6 POLICY zero=accept max=accept unmapped=reject readonly=reject overflow=reject noncanonical=reject wrong-subject=reject stale=reject atomic=PASS' 'LEANOS/6 CLEANUP omitted=detected wrappers=checked entry=clac result=PASS' 'LEANOS/6 COPY direction=in length=4 cross-page=1 validated=1 user-df=1 kernel-df=cleared ac=cleared result=PASS' 'LEANOS/6 COPY direction=out length=4 cross-page=0 validated=1 user-df=1 kernel-df=cleared destination=verified-by-cpl3 ac=cleared result=PASS' 'LEANOS/5 ENTRY subject=1 address-space=1 cpl=3 yielding=0' 'LEANOS/5 TIMER vector=32 source=pit mode=one-shot origin=cpl3 accepted=1' 'LEANOS/5 CONTEXT old-subject=1 old-address-space=1 new-subject=2 new-address-space=2 policy=round-robin' 'LEANOS/8 PAGING root=B selected=1 result=PASS' 'LEANOS/5 SWITCH subject=2 address-space=2 cr3=switched stack=restored ticks-masked=1' 'LEANOS/5 SYSCALL subject=2 caller=2 address-space=2 authorized=1 canaries=preserved' 'LEANOS/5 FINAL status=PASS ticks=1' >> "$log"; exit 33;;
missing-paging) set +e; LEANOS_QEMU_FIXTURE_MODE=success "$0" "$@"; set -e; sed -i '/LEANOS\/8 PAGING/d' "$log"; exit 33;;
missing-scrub) set +e; LEANOS_QEMU_FIXTURE_MODE=success "$0" "$@"; set -e; sed -i '/LEANOS\/7 SCRUB/d' "$log"; exit 33;;
wrong-memory-map) set +e; LEANOS_QEMU_FIXTURE_MODE=success "$0" "$@"; set -e; sed -i 's/reported-top-mib=[0-9]*/reported-top-mib=32/' "$log"; exit 33;;
reordered-allocation) set +e; LEANOS_QEMU_FIXTURE_MODE=success "$0" "$@"; set -e; sed -i 's|LEANOS/7 SCRUB bytes=4096 zero=1 result=PASS|__SCRUB__|; s|LEANOS/7 PUBLISH object=1 owner=1 stale-object=denied result=PASS|LEANOS/7 SCRUB bytes=4096 zero=1 result=PASS|; s|__SCRUB__|LEANOS/7 PUBLISH object=1 owner=1 stale-object=denied result=PASS|' "$log"; exit 33;;
interrupts-disabled|timer-missing) set +e; LEANOS_QEMU_FIXTURE_MODE=success "$0" "$@"; set -e; sed -i '/LEANOS\/5 TIMER/d' "$log"; exit 33;;
old-resumed) set +e; LEANOS_QEMU_FIXTURE_MODE=success "$0" "$@"; set -e; sed -i 's/SWITCH subject=2/SWITCH subject=1/' "$log"; exit 33;;
wrong-binding) set +e; LEANOS_QEMU_FIXTURE_MODE=success "$0" "$@"; set -e; sed -i 's/caller=2 address-space=2/caller=1 address-space=1/' "$log"; exit 33;;
duplicate-tick) set +e; LEANOS_QEMU_FIXTURE_MODE=success "$0" "$@"; set -e; sed -i '/LEANOS\/5 TIMER/p' "$log"; exit 33;;
corrupt-canary) set +e; LEANOS_QEMU_FIXTURE_MODE=success "$0" "$@"; set -e; sed -i 's/canaries=preserved/canaries=corrupt/' "$log"; exit 33;;
skipped-user) printf '%s\n' 'LEANOS/2 BOOT target=x86_64-q35 entry=int80' 'LEANOS/2 TRANSITION state=0 command=1 result=1' 'LEANOS/2 TRANSITION state=0 command=7 result=0' 'LEANOS/2 SYSCALL kind=authorized result=accepted' 'LEANOS/2 SYSCALL kind=forged result=rejected' 'LEANOS/2 FAULT vector=14 class=user-supervisor-access contained=1' 'LEANOS/2 RESUME kernel=1' 'LEANOS/2 FINAL status=PASS' > "$log"; exit 33;;
forged-result) printf '%s\n' 'LEANOS/2 BOOT target=x86_64-q35 entry=int80' 'LEANOS/2 TRANSITION state=0 command=1 result=1' 'LEANOS/2 TRANSITION state=0 command=7 result=0' 'LEANOS/2 USER cpl=3' 'LEANOS/2 SYSCALL kind=authorized result=accepted' 'LEANOS/2 SYSCALL kind=forged result=accepted' 'LEANOS/2 FAULT vector=14 class=user-supervisor-access contained=1' 'LEANOS/2 RESUME kernel=1' 'LEANOS/2 FINAL status=PASS' > "$log"; exit 33;;
reordered) printf '%s\n' 'LEANOS/2 BOOT target=x86_64-q35 entry=int80' 'LEANOS/2 TRANSITION state=0 command=1 result=1' 'LEANOS/2 TRANSITION state=0 command=7 result=0' 'LEANOS/2 USER cpl=3' 'LEANOS/2 SYSCALL kind=forged result=rejected' 'LEANOS/2 SYSCALL kind=authorized result=accepted' 'LEANOS/2 FAULT vector=14 class=user-supervisor-access contained=1' 'LEANOS/2 RESUME kernel=1' 'LEANOS/2 FINAL status=PASS' > "$log"; exit 33;;
wrong-fault) printf '%s\n' 'LEANOS/2 BOOT target=x86_64-q35 entry=int80' 'LEANOS/2 TRANSITION state=0 command=1 result=1' 'LEANOS/2 TRANSITION state=0 command=7 result=0' 'LEANOS/2 USER cpl=3' 'LEANOS/2 SYSCALL kind=authorized result=accepted' 'LEANOS/2 SYSCALL kind=forged result=rejected' 'LEANOS/2 FAULT vector=13 class=general-protection contained=1' 'LEANOS/2 RESUME kernel=1' 'LEANOS/2 FINAL status=PASS' > "$log"; exit 33;;
missing) : > "$log"; exit 33;;
partial) echo 'LEANOS/2 BOOT target=x86_64-q35 entry=int80' > "$log"; exit 33;;
guest-error) echo 'LEANOS/2 FINAL status=FAIL' > "$log"; exit 35;;
hang) sleep 10;;
*) exit 2;; esac
