#!/usr/bin/env bash
set -euo pipefail
[[ "${1:-}" == --version ]] && { echo "QEMU fixture version 1"; exit 0; }
log=""; for arg in "$@"; do [[ "$arg" == file:* ]] && log="${arg#file:}"; done
[[ -n "$log" ]] || exit 2
case "${LEANOS_QEMU_FIXTURE_MODE:-success}" in
success) echo 'LEANOS/4 BOOT target=x86_64-q35 subjects=2 schedule=fixed controls=wp,smep' > "$log"; awk -F '\t' '$1 ~ /^[0-9]+$/ { print "LEANOS/3 ORACLE id=" $2 " result=PASS" }' "$LEANOS_ORACLE_CORPUS" >> "$log"; tail -n +4 scripts/run-image.sh >/dev/null; printf '%s\n' 'LEANOS/4 CONTROL cr0.wp=1 cr4.smep=1 stage=exception-path-ready' 'LEANOS/4 PROBE kind=wp vector=14 error=3 origin=kernel address=kernel-text policy=fatal result=PASS' 'LEANOS/4 PROBE kind=smep vector=14 error=17 origin=kernel address=user-a-text policy=fatal result=PASS' 'LEANOS/3 SUBJECT id=1 address-space=1 cpl=3' 'LEANOS/3 IPC op=receive subject=1 result=denied reason=missing-receive' 'LEANOS/3 IPC op=send subject=1 result=accepted payload=4c45414e:4f53 supplied-sender=99' 'LEANOS/3 HANDOFF from=1 to=2 address-space=2 cr3=switched' 'LEANOS/3 SUBJECT id=2 address-space=2 cpl=3' 'LEANOS/3 IPC op=send subject=2 result=denied reason=missing-send' 'LEANOS/3 IPC op=receive subject=2 result=delivered sender=1 payload=4c45414e:4f53' 'LEANOS/3 IPC supplied-sender=99 trusted=0 capability-transfer=none' 'LEANOS/3 FAULT subject=2 vector=14 class=user-supervisor-access contained=1' 'LEANOS/3 RESUME kernel=1' 'LEANOS/3 FINAL status=PASS' >> "$log"; exit 33;;
skipped-user) printf '%s\n' 'LEANOS/2 BOOT target=x86_64-q35 entry=int80' 'LEANOS/2 TRANSITION state=0 command=1 result=1' 'LEANOS/2 TRANSITION state=0 command=7 result=0' 'LEANOS/2 SYSCALL kind=authorized result=accepted' 'LEANOS/2 SYSCALL kind=forged result=rejected' 'LEANOS/2 FAULT vector=14 class=user-supervisor-access contained=1' 'LEANOS/2 RESUME kernel=1' 'LEANOS/2 FINAL status=PASS' > "$log"; exit 33;;
forged-result) printf '%s\n' 'LEANOS/2 BOOT target=x86_64-q35 entry=int80' 'LEANOS/2 TRANSITION state=0 command=1 result=1' 'LEANOS/2 TRANSITION state=0 command=7 result=0' 'LEANOS/2 USER cpl=3' 'LEANOS/2 SYSCALL kind=authorized result=accepted' 'LEANOS/2 SYSCALL kind=forged result=accepted' 'LEANOS/2 FAULT vector=14 class=user-supervisor-access contained=1' 'LEANOS/2 RESUME kernel=1' 'LEANOS/2 FINAL status=PASS' > "$log"; exit 33;;
reordered) printf '%s\n' 'LEANOS/2 BOOT target=x86_64-q35 entry=int80' 'LEANOS/2 TRANSITION state=0 command=1 result=1' 'LEANOS/2 TRANSITION state=0 command=7 result=0' 'LEANOS/2 USER cpl=3' 'LEANOS/2 SYSCALL kind=forged result=rejected' 'LEANOS/2 SYSCALL kind=authorized result=accepted' 'LEANOS/2 FAULT vector=14 class=user-supervisor-access contained=1' 'LEANOS/2 RESUME kernel=1' 'LEANOS/2 FINAL status=PASS' > "$log"; exit 33;;
wrong-fault) printf '%s\n' 'LEANOS/2 BOOT target=x86_64-q35 entry=int80' 'LEANOS/2 TRANSITION state=0 command=1 result=1' 'LEANOS/2 TRANSITION state=0 command=7 result=0' 'LEANOS/2 USER cpl=3' 'LEANOS/2 SYSCALL kind=authorized result=accepted' 'LEANOS/2 SYSCALL kind=forged result=rejected' 'LEANOS/2 FAULT vector=13 class=general-protection contained=1' 'LEANOS/2 RESUME kernel=1' 'LEANOS/2 FINAL status=PASS' > "$log"; exit 33;;
missing) : > "$log"; exit 33;;
partial) echo 'LEANOS/2 BOOT target=x86_64-q35 entry=int80' > "$log"; exit 33;;
guest-error) echo 'LEANOS/2 FINAL status=FAIL' > "$log"; exit 35;;
hang) sleep 10;;
*) exit 2;; esac
