#!/usr/bin/env python3
"""Mechanically extract the N-PHY rev3 table data from brcmsmac phytbl_n.c
and emit LeanOS/Wifi/NPhyTablesData.lean.

usage: gen_nphy_tables.py <brcmsmac>/phy/phytbl_n.c LeanOS/Wifi/NPhyTablesData.lean
"""
import re, sys

SRC = sys.argv[1]
OUT = sys.argv[2]
text = open(SRC).read()
# strip comments
text = re.sub(r'/\*.*?\*/', '', text, flags=re.S)
text = re.sub(r'//[^\n]*', '', text)

def lower_camel(name):
    parts = name.split('_')
    return parts[0] + ''.join(p[:1].upper() + p[1:] for p in parts[1:])

def array(name):
    m = re.search(r'(?:static\s+)?const\s+u(8|16|32)\s+' + re.escape(name) +
                  r'\s*\[\s*\]\s*=\s*\{(.*?)\};', text, flags=re.S)
    assert m, name
    bits = int(m.group(1))
    toks = [t.strip() for t in m.group(2).split(',')]
    if toks and toks[-1] == '':
        toks = toks[:-1]
    vals = []
    for t in toks:
        assert re.fullmatch(r'0[xX][0-9a-fA-F]+|[0-9]+', t), (name, t)
        v = int(t, 0)
        assert 0 <= v < (1 << bits), (name, t)
        vals.append(v)
    # independent cross-check of the element count
    assert len(vals) == len(re.findall(r'\b(?:0[xX][0-9a-fA-F]+|[0-9]+)\b', m.group(2))), name
    return bits, vals

def info(name):
    m = re.search(r'const\s+struct\s+phytbl_info\s+' + re.escape(name) +
                  r'\s*\[\s*\]\s*=\s*\{(.*?)\};', text, flags=re.S)
    assert m, name
    ents = re.findall(r'\{\s*&(\w+)\s*,\s*ARRAY_SIZE\((\w+)\)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\}',
                      m.group(1))
    assert len(ents) == m.group(1).count('{'), name
    out = []
    for arr, arr2, tid, off, width in ents:
        assert arr == arr2
        out.append((arr, int(tid), int(off), int(width)))
    return out

def hexstr(vals, bits):
    w = bits // 4
    lines = []
    for i in range(0, len(vals), 8):
        lines.append(' '.join('%0*x' % (w, v) for v in vals[i:i + 8]))
    return '\n'.join(lines)

static = info('mimophytbl_info_rev3')
vol = [info('mimophytbl_info_rev3_volatile' + s) for s in ['', '1', '2', '3']]
for v in vol:
    assert len(v) == 1

arrays = [e[0] for e in static] + [v[0][0] for v in vol]
defs = []
total_static = 0
for name in arrays:
    bits, vals = array(name)
    defs.append((name, bits, vals))

def spec(ent, lens):
    arr, tid, off, width = ent
    bits = lens[arr][0]
    assert bits == width, (arr, bits, width)
    return ('  { name := "%s", data := %s, len := %d, id := %d, offset := %d, width := %d }'
            % (arr, lower_camel(arr), len(lens[arr][1]), tid, off, width))

lens = {n: (b, v) for n, b, v in defs}
o = []
o.append('''/-
N-PHY revision 3+ PHY table data (generated by
`hardware/wifi/tools/gen_nphy_tables.py`; do not edit by hand).

Ported from Linux brcmsmac (ISC license), Copyright (c) 2010 Broadcom
Corporation; see drivers/net/wireless/broadcom/brcm80211/brcmsmac at Linux
commit fd179f8a05be3ccae366b9b96e176b51fbe54aab.

Extracted mechanically from `phy/phytbl_n.c`: the arrays referenced by
`mimophytbl_info_rev3` and `mimophytbl_info_rev3_volatile{,1,2,3}`. Each
array is carried as a hexadecimal string decoded by `hexU32s` at generation
time; `len` is the C array length (`ARRAY_SIZE`), checked by the writer.
-/
namespace LeanOS.Wifi.NPhyTablesData

/-- One `struct phytbl_info` entry: table data plus id, offset and element
width (8, 16 or 32 bits). -/
structure TblSpec where
  name : String
  data : String
  len : Nat
  id : UInt32
  offset : UInt32
  width : UInt32
''')
for name, bits, vals in defs:
    o.append('/-- `%s` (u%d, %d elements). -/' % (name, bits, len(vals)))
    o.append('def %s : String := "\n%s"\n' % (lower_camel(name), hexstr(vals, bits)))
o.append('/-- `mimophytbl_info_rev3` (phytbl_n.c), written by '
         '`wlc_phy_static_table_download_nphy` for revisions 3..6. -/')
o.append('def mimophytblInfoRev3 : Array TblSpec := #[')
o.append(',\n'.join(spec(e, lens) for e in static))
o.append(']\n')
for i, (s, v) in enumerate(zip(['', '1', '2', '3'], vol)):
    o.append('/-- `mimophytbl_info_rev3_volatile%s[0]`: antenna switch control '
             'table for SROM antswctrllut %d. -/' % (s, i))
    o.append('def mimophytblInfoRev3Volatile%s : TblSpec :=\n%s\n' % (s, spec(v[0], lens)))
o.append('end LeanOS.Wifi.NPhyTablesData')
open(OUT, 'w').write('\n'.join(o) + '\n')

tot = sum(len(lens[e[0]][1]) for e in static)
print('static entries', len(static), 'elements', tot)
for e in static:
    print('  %-26s id=%2d off=%3d w=%2d n=%d' % (e[0], e[1], e[2], e[3], len(lens[e[0]][1])))
for v in vol:
    e = v[0]
    print('  %-26s id=%2d off=%3d w=%2d n=%d' % (e[0], e[1], e[2], e[3], len(lens[e[0]][1])))
