#!/usr/bin/env python3
"""Generate the shared-object portion of the LeanOS image Make graph."""

from __future__ import annotations

import argparse
from pathlib import Path
import shlex


GENERATED_MODULES = (
    "KernelTransition",
    "Syscall",
    "IPCSyscall",
    "Preemption",
    "BootAllocation",
    "BootMemoryMapStreaming",
    "BootMemoryMapStreamAuthority",
    "BootTopology",
    "Interrupt",
    "InterruptEntry",
    "BlockingIPC",
    "CapabilityReuse",
    "ExtendedState",
    "PrivilegeEntryControl",
    "FaultDispatch",
    "DirectPortIO",
    "StaleTranslation",
    "FrameBudgetScenario",
    "CompositeDispatcher",
    "VTdBootPlan",
    "IOTLB",
)

BOOT_ALLOCATION_PARTS = (
    "BootAllocation",
    "BootMemoryMapStreaming",
    "BootMemoryMapStreamAuthority",
    "BootTopology",
)

FAULT_DISPATCH_PARTS = (
    "FaultDispatch",
    "DirectPortIO",
    "StaleTranslation",
    "FrameBudgetScenario",
    "CompositeDispatcher",
    "VTdBootPlan",
    "IOTLB",
)


def make_escape(value: str) -> str:
    return value.replace("$", "$$").replace(" ", "\\ ").replace("#", "\\#")


def shell_join(arguments: list[str]) -> str:
    return " ".join(shlex.quote(argument) for argument in arguments)


def render_graph(build_dir: Path, cc: str, cflags: list[str], lean_prefix: Path) -> str:
    build = make_escape(str(build_dir))
    compile_flags = shell_join([*cflags, f"-I{lean_prefix / 'include'}"])
    lines = [
        "# Generated by scripts/generate-image-object-graph.py; do not edit.",
        f"IMAGE_CC := {shlex.quote(cc)}",
        f"IMAGE_CFLAGS := {compile_flags}",
        "",
    ]

    combined = set(BOOT_ALLOCATION_PARTS) | set(FAULT_DISPATCH_PARTS)
    for module in GENERATED_MODULES:
        object_name = f"{module}.part.o" if module in combined else f"{module}.o"
        lines.extend(
            [
                f"{build}/{object_name}: {build}/{module}.c",
                "\t$(IMAGE_CC) $(IMAGE_CFLAGS) -MMD -MP -MF $@.d -c $< -o $@",
            ]
        )

    boot_inputs = " ".join(
        f"{build}/{module}.part.o" for module in BOOT_ALLOCATION_PARTS
    )
    fault_inputs = " ".join(
        f"{build}/{module}.part.o" for module in FAULT_DISPATCH_PARTS
    )
    lines.extend(
        [
            f"{build}/BootAllocation.o: {boot_inputs}",
            "\tld -r $^ -o $@",
            f"{build}/FaultDispatch.o: {fault_inputs}",
            "\tld -r $^ -o $@",
            "",
            ".PHONY: shared-generated-objects",
            "shared-generated-objects: "
            + " ".join(
                f"{build}/{module}.o"
                for module in GENERATED_MODULES
                if module not in combined
            )
            + f" {build}/BootAllocation.o {build}/FaultDispatch.o",
            "",
            "-include "
            + " ".join(
                f"{build}/{module}.{'part.o' if module in combined else 'o'}.d"
                for module in GENERATED_MODULES
            ),
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--build-dir", type=Path, required=True)
    parser.add_argument("--cc", required=True)
    parser.add_argument("--lean-prefix", type=Path, required=True)
    parser.add_argument("--cflag", action="append", default=[])
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    graph = render_graph(args.build_dir, args.cc, args.cflag, args.lean_prefix)
    args.output.write_text(graph, encoding="utf-8")


if __name__ == "__main__":
    main()
