#!/usr/bin/env bash
# Controlled negatives for the generated boundary vocabulary: the token and
# prototype renderers reject malformed, duplicate, or lying rows; an arity
# mismatch against the generated prototypes fails to compile; no hand-written
# copy of a token or an exported prototype survives in the C sources; and a
# stale generated header is regenerated by the memoized generator.
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
cc_command="${LEANOS_HOST_CC:-cc}"
tab=$'\t'

expect_rejection() {
  local renderer="$1" diagnostic="$2" input="$3"
  if printf '%b' "$input" | awk -f "$renderer" > /dev/null 2> "$tmp/error"; then
    echo "error: $renderer accepted: $diagnostic" >&2
    exit 1
  fi
  grep -Fxq "error: $diagnostic" "$tmp/error" || {
    echo "error: $renderer failed without the expected diagnostic: $diagnostic" >&2
    cat "$tmp/error" >&2
    exit 1
  }
}

tokens='leanos-vocabulary\t1\nsource-revision\ttest\n'
printf '%b' "${tokens}token\tSTATE\tCOMPOSITE_STATE_INITIAL\t1\tUINT64_C(0x0001)\ntoken\tSCALAR\tCOMPOSITE_INPUT_WORDS\t6\t6U\n" |
  awk -f scripts/render-composite-tokens.awk > "$tmp/tokens.h"
grep -Fxq '#define LEANOS_COMPOSITE_STATE_INITIAL UINT64_C(0x0001)' "$tmp/tokens.h"
grep -Fxq '#define LEANOS_COMPOSITE_INPUT_WORDS 6U' "$tmp/tokens.h"
grep -Fxq '#define LEANOS_COMPOSITE_TOKEN_COUNT 2U' "$tmp/tokens.h"
expect_rejection scripts/render-composite-tokens.awk \
  "unexpected boundary vocabulary schema: leanos-vocabulary${tab}2" \
  'leanos-vocabulary\t2\ntoken\tSTATE\tA\t1\tUINT64_C(0x0001)\n'
expect_rejection scripts/render-composite-tokens.awk \
  'duplicate generated token name: COMPOSITE_STATE_INITIAL' \
  "${tokens}token\tSTATE\tCOMPOSITE_STATE_INITIAL\t1\tUINT64_C(0x0001)\ntoken\tSTATE\tCOMPOSITE_STATE_INITIAL\t257\tUINT64_C(0x0101)\n"
expect_rejection scripts/render-composite-tokens.awk \
  'generated token literal does not denote its word: COMPOSITE_STATE_INITIAL' \
  "${tokens}token\tSTATE\tCOMPOSITE_STATE_INITIAL\t1\tUINT64_C(0x0101)\n"
expect_rejection scripts/render-composite-tokens.awk \
  "malformed generated token row: token${tab}STATE${tab}lower_case${tab}1${tab}UINT64_C(0x0001)" \
  "${tokens}token\tSTATE\tlower_case\t1\tUINT64_C(0x0001)\n"
expect_rejection scripts/render-composite-tokens.awk \
  'generated boundary vocabulary is empty' "$tokens"

abi='leanos-abi\t1\nsource-revision\ttest\n'
printf '%b' "${abi}export\tleanos_boot_transition\t2\tLeanOS.KernelTransition.bootTransition\tLeanOS.KernelTransition\nobject-export\tleanos_boot_handoff_query\tu64,u64,ByteArray,u64,u64\tLeanOS.BootMemoryMapDecoderABI.query\tLeanOS.BootMemoryMapDecoderABI\n" |
  awk -f scripts/render-boundary-abi.awk > "$tmp/abi.h"
grep -Fxq 'uint64_t leanos_boot_transition(uint64_t, uint64_t);' "$tmp/abi.h"
grep -Fxq '  X(leanos_boot_transition, 2)' "$tmp/abi.h"
grep -Fq 'uint64_t leanos_boot_handoff_query(uint64_t, uint64_t, lean_object *,' "$tmp/abi.h"
expect_rejection scripts/render-boundary-abi.awk \
  'duplicate generated export symbol: leanos_boot_transition' \
  "${abi}export\tleanos_boot_transition\t2\ta\tb\nexport\tleanos_boot_transition\t3\ta\tb\n"
expect_rejection scripts/render-boundary-abi.awk \
  'malformed generated export arity: leanos_boot_transition' \
  "${abi}export\tleanos_boot_transition\ttwo\ta\tb\n"
expect_rejection scripts/render-boundary-abi.awk \
  'unsupported generated object export parameter: leanos_boot_handoff_query Array' \
  "${abi}object-export\tleanos_boot_handoff_query\tArray,u64\ta\tb\n"
expect_rejection scripts/render-boundary-abi.awk \
  'generated boundary abi lists no scalar exports' "$abi"

# An arity mismatch against the generated prototypes is a compile error; the
# exact arity compiles.
cat > "$tmp/caller.c" <<'CALLER'
#include "abi.h"
uint64_t caller(void) { return leanos_boot_transition(1); }
CALLER
if "$cc_command" -std=c11 -Wall -Wextra -Werror -fsyntax-only -I"$tmp" "$tmp/caller.c" \
    2> "$tmp/error"; then
  echo "error: arity mismatch against the generated prototype compiled" >&2
  exit 1
fi
cat > "$tmp/caller.c" <<'CALLER'
#include "abi.h"
uint64_t caller(void) { return leanos_boot_transition(1, 2); }
CALLER
"$cc_command" -std=c11 -Wall -Wextra -Werror -fsyntax-only -I"$tmp" "$tmp/caller.c"
# The hosted object prototypes are hidden from freestanding consumers.
printf '#include "abi.h"\nuint64_t caller(void) { return leanos_boot_handoff_query(0, 0, 0, 0); }\n' \
  > "$tmp/caller.c"
if "$cc_command" -std=c11 -Wall -Wextra -Werror -fsyntax-only -I"$tmp" "$tmp/caller.c" \
    2> /dev/null; then
  echo "error: object export prototype leaked into a freestanding consumer" >&2
  exit 1
fi

# The memoized generator replaces a stale or corrupted generated header.
LEANOS_ORACLE_TOOL_SIGNATURE=test ./scripts/generate-oracle.sh "$tmp/out" > /dev/null
cp "$tmp/out/composite-tokens.h" "$tmp/tokens.expected"
cp "$tmp/out/boundary-abi.h" "$tmp/abi.expected"
printf '#define LEANOS_COMPOSITE_STATE_INITIAL UINT64_C(0x0002)\n' >> "$tmp/out/composite-tokens.h"
echo 'uint64_t leanos_stale(void);' >> "$tmp/out/boundary-abi.h"
LEANOS_ORACLE_TOOL_SIGNATURE=test ./scripts/generate-oracle.sh "$tmp/out" > /dev/null
cmp -s "$tmp/out/composite-tokens.h" "$tmp/tokens.expected"
cmp -s "$tmp/out/boundary-abi.h" "$tmp/abi.expected"
grep -Fxq '#define LEANOS_COMPOSITE_STATE_COUNT 71U' "$tmp/out/composite-tokens.h"
test "$(grep -c '^uint64_t leanos_' "$tmp/out/boundary-abi.h")" -eq 65

# No hand-maintained copy of a boundary token or an exported prototype may
# remain in the C sources; the checked-in dispatcher header carries prose
# only.  The token names come from the generated vocabulary itself, so every
# generated constant is covered exactly, and the family prefixes catch a
# hand-written token that was never generated.  The scan runs over an
# explicit list of existing files, and a grep error (a missing operand, for
# example) fails the gate instead of passing as "no match".
generated_names="$(awk -F '\t' '$1 == "token" { print $3 }' "$tmp/out/vocabulary.tsv" |
  paste -sd '|')"
test -n "$generated_names"
hand_copy_pattern="^[[:space:]]*(#define[[:space:]]+LEANOS_(($generated_names)([^A-Za-z0-9_]|\$)|COMPOSITE_(STATE|COMMAND|REPLY|ERROR)_|FRAME_BUDGET_)|(extern[[:space:]]+)?uint64_t[[:space:]]+leanos_[a-z0-9_]+[[:space:]]*\()"
reject_hand_copies() {
  local status=0
  grep -En "$hand_copy_pattern" "$@" > "$tmp/hand-copies" 2> "$tmp/hand-copies.error" ||
    status=$?
  if [[ $status -eq 0 ]]; then
    cat "$tmp/hand-copies" >&2
    echo "error: hand-maintained boundary vocabulary copy in C sources" >&2
    return 1
  elif [[ $status -ne 1 ]]; then
    cat "$tmp/hand-copies.error" >&2
    echo "error: hand-copy scan did not complete (grep status $status)" >&2
    return 1
  fi
}
mapfile -t c_sources < <(
  find include boot tests -type f \( -name '*.c' -o -name '*.h' \) | sort
)
test "${#c_sources[@]}" -gt 0
reject_hand_copies "${c_sources[@]}"
[[ ! -e boot/generated-boundary-abi.h ]]
for mutation in \
  '#define LEANOS_COMPOSITE_STATE_INITIAL UINT64_C(0x0001)' \
  '#define LEANOS_COMPOSITE_ABI_VERSION UINT64_C(1)' \
  '#define LEANOS_COMPOSITE_DELIVERED_HANDLE UINT64_C(0x60003)' \
  '#define LEANOS_COMPOSITE_STATE_COUNT 71U' \
  '#define LEANOS_FRAME_BUDGET_TERMINATE_FLUSH_TOKEN UINT64_C(0xfb00444401)' \
  '#define LEANOS_COMPOSITE_REPLY_NEVER_GENERATED UINT64_C(0x1)' \
  'extern uint64_t leanos_boot_transition(uint64_t, uint64_t);' \
  'uint64_t leanos_boot_transition(uint64_t, uint64_t);'; do
  printf '%s\n' "$mutation" > "$tmp/mutated.c"
  if reject_hand_copies "$tmp/mutated.c" 2> /dev/null; then
    echo "error: a hand-written boundary copy was not rejected: $mutation" >&2
    exit 1
  fi
done
printf '#define LEANOS_COMPOSITE_DISPATCHER_H\n#define LEANOS_ORACLE_DISPATCH_ATTRIBUTES inline\n' \
  > "$tmp/benign.h"
reject_hand_copies "$tmp/benign.h"
if reject_hand_copies "$tmp/benign.h" "$tmp/does-not-exist.h" 2> /dev/null; then
  echo "error: a scan error (missing operand) was accepted as a clean scan" >&2
  exit 1
fi
echo "Generated boundary vocabulary rejects drift and hand-maintained copies"
