#ifndef LEANOS_COMPOSITE_DISPATCHER_H
#define LEANOS_COMPOSITE_DISPATCHER_H

#include <stdint.h>

/*
 * Version-one scalar ABI for LeanOS.CompositeDispatcher.dispatch.
 *
 * Input words are ordered as the canonical name of a complete bounded
 * CompositeState, command tag, then arguments 0..3. Lean reconstructs the
 * complete state by authoritative replay; callers cannot supply individual
 * state projections or post-state fragments. The result canonically names
 * the exact typed authoritativeGate result and next state.
 *
 * All fields are logical uint64_t values. There are no caller-owned buffers,
 * so state/result aliasing, alignment, pointer identity, and partial writes are
 * inapplicable. Calls are pure, reentrant, and have no generated state cell.
 * Exactly six input words are required by the surrounding corpus format;
 * truncation is rejected by that caller before this scalar function is called.
 *
 * Every state and command word has ABI version 1 in bits 0..7. State bits
 * 8..15 select one of 59 canonical states and all upper bits are reserved.
 * Command tags use bits 8..15 to select one of 62 commands and all upper
 * bits are reserved. Arguments not named by a command must be zero. A success
 * result uses bits 0..7 for the version, 8..15 for the next-state selector,
 * 16..23 for the typed-reply selector, and reserves bits 24..63. Error words
 * are the closed values listed below and never authorize an operation.
 */
#define LEANOS_COMPOSITE_ABI_VERSION UINT64_C(1)
#define LEANOS_COMPOSITE_INPUT_WORDS 6U
#define LEANOS_COMPOSITE_RESULT_WORDS 1U
#define LEANOS_COMPOSITE_STATE_COUNT 59U
#define LEANOS_COMPOSITE_COMMAND_COUNT 62U

#define LEANOS_COMPOSITE_STATE_INITIAL UINT64_C(0x0001)
#define LEANOS_COMPOSITE_STATE_SUBJECT_CREATED UINT64_C(0x0101)
#define LEANOS_COMPOSITE_STATE_UNKNOWN_SYSCALL_REJECTED UINT64_C(0x0201)
#define LEANOS_COMPOSITE_STATE_MALFORMED_MAP_REJECTED UINT64_C(0x0301)
#define LEANOS_COMPOSITE_STATE_SCHEDULER_OBSERVED UINT64_C(0x0401)
#define LEANOS_COMPOSITE_STATE_SUBJECT_TERMINATED UINT64_C(0x0501)
#define LEANOS_COMPOSITE_STATE_FATAL_ENTERED UINT64_C(0x0601)
#define LEANOS_COMPOSITE_STATE_POST_FATAL_REJECTED UINT64_C(0x0701)

#define LEANOS_COMPOSITE_STATE_MIXED_INITIAL UINT64_C(0x0801)
#define LEANOS_COMPOSITE_STATE_TRANSFER_OFFERED UINT64_C(0x0901)
#define LEANOS_COMPOSITE_STATE_TRANSFER_ACCEPTED UINT64_C(0x0a01)
#define LEANOS_COMPOSITE_STATE_TRANSFER_REVOKED UINT64_C(0x0b01)
#define LEANOS_COMPOSITE_STATE_STALE_HANDLE_REJECTED UINT64_C(0x0c01)
#define LEANOS_COMPOSITE_STATE_FRESH_CAPABILITY_COPIED UINT64_C(0x0d01)
#define LEANOS_COMPOSITE_STATE_SYSCALL_MAPPED UINT64_C(0x0e01)
#define LEANOS_COMPOSITE_STATE_DIRECT_MAPPED UINT64_C(0x0f01)
#define LEANOS_COMPOSITE_STATE_MIXED_UNKNOWN_SYSCALL_REJECTED UINT64_C(0x1001)
#define LEANOS_COMPOSITE_STATE_NONBLOCKING_SENT UINT64_C(0x1101)
#define LEANOS_COMPOSITE_STATE_NONBLOCKING_RECEIVED UINT64_C(0x1201)
#define LEANOS_COMPOSITE_STATE_BLOCKING_RECEIVER_BLOCKED UINT64_C(0x1301)
#define LEANOS_COMPOSITE_STATE_BLOCKING_RECEIVER_WOKEN UINT64_C(0x1401)
#define LEANOS_COMPOSITE_STATE_TIMER_SWITCHED UINT64_C(0x1501)
#define LEANOS_COMPOSITE_STATE_USER_FAULT_CLEANED UINT64_C(0x1601)
#define LEANOS_COMPOSITE_STATE_MIXED_FATAL_ENTERED UINT64_C(0x1701)
#define LEANOS_COMPOSITE_STATE_MIXED_POST_FATAL_REJECTED UINT64_C(0x1801)
#define LEANOS_COMPOSITE_STATE_PAGE_UNMAPPED UINT64_C(0x1901)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_INITIAL UINT64_C(0x1a01)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_WRONG_OWNER_REJECTED UINT64_C(0x1b01)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_PROTECT_PENDING UINT64_C(0x1c01)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_PROTECT_MISMATCH_REJECTED UINT64_C(0x1d01)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_PROTECTED UINT64_C(0x1e01)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_RELEASE_PENDING UINT64_C(0x1f01)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_RELEASE_MISMATCH_REJECTED UINT64_C(0x2001)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_RELEASED UINT64_C(0x2101)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_STALE_RELEASE_REJECTED UINT64_C(0x2201)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_DESTROY_PENDING UINT64_C(0x2301)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_DESTROYED UINT64_C(0x2401)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_SWITCH_PENDING UINT64_C(0x2501)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_SWITCHED UINT64_C(0x2601)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_REUSED UINT64_C(0x2701)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_UNMAP_PENDING UINT64_C(0x2801)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_UNMAPPED UINT64_C(0x2901)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_SWITCH_AWAY_PENDING UINT64_C(0x2a01)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_SWITCHED_AWAY UINT64_C(0x2b01)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_SWITCH_BACK_PENDING UINT64_C(0x2c01)
#define LEANOS_COMPOSITE_STATE_INVALIDATION_SWITCHED_BACK UINT64_C(0x2d01)
#define LEANOS_COMPOSITE_STATE_PAGE_PROTECTED UINT64_C(0x2e01)

#define LEANOS_COMPOSITE_STATE_BUDGET_INITIAL UINT64_C(0x4001)
#define LEANOS_COMPOSITE_STATE_BUDGET_A_ALLOCATED UINT64_C(0x4101)
#define LEANOS_COMPOSITE_STATE_BUDGET_A_EXHAUSTED UINT64_C(0x4201)
#define LEANOS_COMPOSITE_STATE_BUDGET_B_SELECTED UINT64_C(0x4301)
#define LEANOS_COMPOSITE_STATE_BUDGET_B_ALLOCATED UINT64_C(0x4401)
#define LEANOS_COMPOSITE_STATE_BUDGET_A_TERMINATED UINT64_C(0x4501)
#define LEANOS_COMPOSITE_STATE_BUDGET_B_FRESH UINT64_C(0x4601)
#define LEANOS_COMPOSITE_STATE_BUDGET_STALE_DENIED UINT64_C(0x4701)
#define LEANOS_COMPOSITE_STATE_BUDGET_COMPLETE UINT64_C(0x4801)
#define LEANOS_COMPOSITE_STATE_BUDGET_A_RELEASED UINT64_C(0x4901)
#define LEANOS_COMPOSITE_STATE_BUDGET_RELEASE_DENIED UINT64_C(0x4a01)
#define LEANOS_COMPOSITE_STATE_BUDGET_RELEASE_COMPLETE UINT64_C(0x4b01)

#define LEANOS_COMPOSITE_COMMAND_CREATE_SUBJECT_ONE UINT64_C(0x0101)
#define LEANOS_COMPOSITE_COMMAND_REJECT_UNKNOWN_SYSCALL UINT64_C(0x0201)
#define LEANOS_COMPOSITE_COMMAND_REJECT_MALFORMED_MAP UINT64_C(0x0301)
#define LEANOS_COMPOSITE_COMMAND_OBSERVE_SCHEDULER UINT64_C(0x0401)
#define LEANOS_COMPOSITE_COMMAND_TERMINATE_SUBJECT_ONE UINT64_C(0x0501)
#define LEANOS_COMPOSITE_COMMAND_ENTER_FATAL_KERNEL_FAULT UINT64_C(0x0601)
#define LEANOS_COMPOSITE_COMMAND_ATTEMPT_POST_FATAL_SCHEDULE UINT64_C(0x0701)
#define LEANOS_COMPOSITE_COMMAND_REJECT_STALE_MAP_HANDLE UINT64_C(0x0801)
#define LEANOS_COMPOSITE_COMMAND_REJECT_NONBLOCKING_RECEIVE UINT64_C(0x0901)
#define LEANOS_COMPOSITE_COMMAND_REJECT_CAPABILITY_COPY UINT64_C(0x0a01)
#define LEANOS_COMPOSITE_COMMAND_REJECT_BLOCKING_CANCEL UINT64_C(0x0b01)
#define LEANOS_COMPOSITE_COMMAND_REJECT_DEFERRED_DRAIN UINT64_C(0x0c01)

#define LEANOS_COMPOSITE_COMMAND_TRANSFER_OFFER UINT64_C(0x2001)
#define LEANOS_COMPOSITE_COMMAND_TRANSFER_ACCEPT UINT64_C(0x2101)
#define LEANOS_COMPOSITE_COMMAND_REVOKE_TRANSFERRED UINT64_C(0x2201)
#define LEANOS_COMPOSITE_COMMAND_REJECT_STALE_REUSED_HANDLE UINT64_C(0x2301)
#define LEANOS_COMPOSITE_COMMAND_COPY_FRESH_CAPABILITY UINT64_C(0x2401)
#define LEANOS_COMPOSITE_COMMAND_ACCEPTED_SYSCALL_MAP UINT64_C(0x2501)
#define LEANOS_COMPOSITE_COMMAND_ACCEPTED_DIRECT_MAP UINT64_C(0x2601)
#define LEANOS_COMPOSITE_COMMAND_REJECT_MIXED_UNKNOWN_SYSCALL UINT64_C(0x2701)
#define LEANOS_COMPOSITE_COMMAND_NONBLOCKING_SEND UINT64_C(0x2801)
#define LEANOS_COMPOSITE_COMMAND_NONBLOCKING_RECEIVE UINT64_C(0x2901)
#define LEANOS_COMPOSITE_COMMAND_BLOCKING_RECEIVE UINT64_C(0x2a01)
#define LEANOS_COMPOSITE_COMMAND_BLOCKING_SEND UINT64_C(0x2b01)
#define LEANOS_COMPOSITE_COMMAND_TIMER_SWITCH UINT64_C(0x2c01)
#define LEANOS_COMPOSITE_COMMAND_USER_FAULT_CLEANUP UINT64_C(0x2d01)
#define LEANOS_COMPOSITE_COMMAND_ENTER_MIXED_FATAL UINT64_C(0x2e01)
#define LEANOS_COMPOSITE_COMMAND_ATTEMPT_MIXED_POST_FATAL UINT64_C(0x2f01)
#define LEANOS_COMPOSITE_COMMAND_ACCEPTED_SYSCALL_UNMAP UINT64_C(0x3001)
#define LEANOS_COMPOSITE_COMMAND_REJECT_UNMAPPED_PAGE_UNMAP UINT64_C(0x3101)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_REJECT_WRONG_OWNER UINT64_C(0x3201)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_PREPARE_PROTECT UINT64_C(0x3301)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_REJECT_PROTECT_MISMATCH UINT64_C(0x3401)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_ACK_PROTECT UINT64_C(0x3501)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_PREPARE_RELEASE UINT64_C(0x3601)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_REJECT_RELEASE_MISMATCH UINT64_C(0x3701)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_ACK_RELEASE UINT64_C(0x3801)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_REJECT_STALE_RELEASE UINT64_C(0x3901)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_PREPARE_DESTROY UINT64_C(0x3a01)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_ACK_DESTROY UINT64_C(0x3b01)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_PREPARE_SWITCH UINT64_C(0x3c01)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_ACK_SWITCH UINT64_C(0x3d01)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_PUBLISH_REUSE UINT64_C(0x3e01)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_PREPARE_UNMAP UINT64_C(0x3f01)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_ACK_UNMAP UINT64_C(0x4001)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_PREPARE_SWITCH_AWAY UINT64_C(0x4101)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_ACK_SWITCH_AWAY UINT64_C(0x4201)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_PREPARE_SWITCH_BACK UINT64_C(0x4301)
#define LEANOS_COMPOSITE_COMMAND_INVALIDATION_ACK_SWITCH_BACK UINT64_C(0x4401)
#define LEANOS_COMPOSITE_COMMAND_ACCEPTED_PROTECT UINT64_C(0x4501)
#define LEANOS_COMPOSITE_COMMAND_REJECT_PROTECT_AMPLIFICATION UINT64_C(0x4601)

/*
 * Typed reply/effect meanings for the bounded direct mapping branches.
 * PAGE_UNMAPPED authorizes exactly StaleTranslation.Effect.page(2, 7), while
 * PAGE_PROTECTED authorizes exactly Effect.page(2, 8). The rejection replies
 * are complete-state stutters and authorize Effect.none. These are scalar
 * meanings of Lean-replayed states, not mutable C shadow state.
 */
#define LEANOS_COMPOSITE_REPLY_PAGE_UNMAPPED UINT64_C(0x301901)
#define LEANOS_COMPOSITE_REPLY_UNMAPPED_PAGE_REJECTED UINT64_C(0x310f01)
#define LEANOS_COMPOSITE_REPLY_PAGE_PROTECTED UINT64_C(0x452e01)
#define LEANOS_COMPOSITE_REPLY_PROTECT_AMPLIFICATION_REJECTED UINT64_C(0x462e01)

/* Exact full-state/command authorizations for the two frame-retiring edges. */
#define LEANOS_FRAME_BUDGET_TERMINATE_FLUSH_TOKEN UINT64_C(0xfb00444401)
#define LEANOS_FRAME_BUDGET_RELEASE_FLUSH_TOKEN UINT64_C(0xfb00484801)

/*
 * The invalidation publication sequence retains the published pre-state while
 * an effect is pending. Prepare replies name the checked page/space/flush
 * effect and its fresh logical ticket. An exact acknowledgement advances to
 * the successor; malformed, stale-ticket, wrong-effect, and wrong-state inputs
 * cannot publish. Reuse is enabled only after acknowledged release and
 * destruction. The object-11 reuse is a bounded fixture, not allocator policy.
 */
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_WRONG_OWNER_REJECTED UINT64_C(0x321b01)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_PROTECT_PENDING UINT64_C(0x331c01)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_PROTECT_MISMATCH_REJECTED UINT64_C(0x341d01)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_PROTECTED UINT64_C(0x351e01)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_RELEASE_PENDING UINT64_C(0x361f01)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_RELEASE_MISMATCH_REJECTED UINT64_C(0x372001)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_RELEASED UINT64_C(0x382101)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_STALE_RELEASE_REJECTED UINT64_C(0x392201)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_DESTROY_PENDING UINT64_C(0x3a2301)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_DESTROYED UINT64_C(0x3b2401)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_SWITCH_PENDING UINT64_C(0x3c2501)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_SWITCHED UINT64_C(0x3d2601)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_REUSED UINT64_C(0x3e2701)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_UNMAP_PENDING UINT64_C(0x3f2801)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_UNMAPPED UINT64_C(0x402901)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_SWITCH_AWAY_PENDING UINT64_C(0x412a01)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_SWITCHED_AWAY UINT64_C(0x422b01)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_SWITCH_BACK_PENDING UINT64_C(0x432c01)
#define LEANOS_COMPOSITE_REPLY_INVALIDATION_SWITCHED_BACK UINT64_C(0x442d01)

#define LEANOS_COMPOSITE_COMMAND_BUDGET_ALLOCATE_A UINT64_C(0x4001)
#define LEANOS_COMPOSITE_COMMAND_BUDGET_RETRY_A UINT64_C(0x4101)
#define LEANOS_COMPOSITE_COMMAND_BUDGET_SELECT_B UINT64_C(0x4201)
#define LEANOS_COMPOSITE_COMMAND_BUDGET_ALLOCATE_B UINT64_C(0x4301)
#define LEANOS_COMPOSITE_COMMAND_BUDGET_TERMINATE_A UINT64_C(0x4401)
#define LEANOS_COMPOSITE_COMMAND_BUDGET_PUBLISH_FRESH_B UINT64_C(0x4501)
#define LEANOS_COMPOSITE_COMMAND_BUDGET_DENY_STALE_A UINT64_C(0x4601)
#define LEANOS_COMPOSITE_COMMAND_BUDGET_COMPLETE UINT64_C(0x4701)
#define LEANOS_COMPOSITE_COMMAND_BUDGET_RELEASE_A UINT64_C(0x4801)
#define LEANOS_COMPOSITE_COMMAND_BUDGET_REPEAT_RELEASE_A UINT64_C(0x4901)
#define LEANOS_COMPOSITE_COMMAND_BUDGET_COMPLETE_RELEASED UINT64_C(0x4a01)

#define LEANOS_COMPOSITE_ERROR_WRONG_VERSION UINT64_C(0xff01)
#define LEANOS_COMPOSITE_ERROR_RESERVED_BITS UINT64_C(0xff02)
#define LEANOS_COMPOSITE_ERROR_UNKNOWN_STATE UINT64_C(0xff03)
#define LEANOS_COMPOSITE_ERROR_UNKNOWN_COMMAND UINT64_C(0xff04)
#define LEANOS_COMPOSITE_ERROR_NONCANONICAL_ARGUMENTS UINT64_C(0xff05)
#define LEANOS_COMPOSITE_ERROR_INVALID_SEQUENCE UINT64_C(0xff06)

uint64_t leanos_composite_dispatch(
    uint64_t state,
    uint64_t command,
    uint64_t arg0,
    uint64_t arg1,
    uint64_t arg2,
    uint64_t arg3);

/* Generated policy query for the issue-112 machine publication leaf. */
uint64_t leanos_frame_budget_mapping_page(
    uint64_t state,
    uint64_t command);

/* Generated full-flush authorization; zero denies every noncanonical pair. */
uint64_t leanos_frame_budget_invalidation_effect(
    uint64_t state,
    uint64_t command);

/*
 * Allocation-free generated validation of the exact canonical q35 DMA
 * snapshot. Each manifest slot supplies identity and control words in the
 * compact format documented by LeanOS.CompositeDispatcher.
 */
uint64_t leanos_validate_q35_dma_snapshot(
    uint64_t version,
    uint64_t topology,
    uint64_t identity0,
    uint64_t control0,
    uint64_t identity1,
    uint64_t control1,
    uint64_t identity2,
    uint64_t control2,
    uint64_t identity3,
    uint64_t control3,
    uint64_t identity4,
    uint64_t control4,
    uint64_t identity5,
    uint64_t control5);

#endif
