#ifndef LEANOS_COMPOSITE_DISPATCHER_H
#define LEANOS_COMPOSITE_DISPATCHER_H

#include <stdint.h>

/*
 * Version-one scalar ABI for LeanOS.CompositeDispatcher.dispatch.
 *
 * Input words are ordered as the canonical name of a complete bounded
 * CompositeState, command tag, then arguments 0..3. Lean reconstructs the
 * complete state by authoritative replay; callers cannot supply individual
 * state projections or post-state fragments. The result canonically names
 * the exact typed authoritativeGate result and next state.
 *
 * All fields are logical uint64_t values. There are no caller-owned buffers,
 * so state/result aliasing, alignment, pointer identity, and partial writes are
 * inapplicable. Calls are pure, reentrant, and have no generated state cell.
 * Exactly six input words are required by the surrounding corpus format;
 * truncation is rejected by that caller before this scalar function is called.
 *
 * Every state and command word has ABI version 1 in bits 0..7. State bits
 * 8..15 select one of 25 canonical states and all upper bits are reserved.
 * Command tags use bits 8..15 to select one of 28 commands and all upper
 * bits are reserved. Arguments not named by a command must be zero. A success
 * result uses bits 0..7 for the version, 8..15 for the next-state selector,
 * 16..23 for the typed-reply selector, and reserves bits 24..63. Error words
 * are the closed values listed below and never authorize an operation.
 */
#define LEANOS_COMPOSITE_ABI_VERSION UINT64_C(1)
#define LEANOS_COMPOSITE_INPUT_WORDS 6U
#define LEANOS_COMPOSITE_RESULT_WORDS 1U
#define LEANOS_COMPOSITE_STATE_COUNT 25U
#define LEANOS_COMPOSITE_COMMAND_COUNT 28U

#define LEANOS_COMPOSITE_STATE_INITIAL UINT64_C(0x0001)
#define LEANOS_COMPOSITE_STATE_SUBJECT_CREATED UINT64_C(0x0101)
#define LEANOS_COMPOSITE_STATE_UNKNOWN_SYSCALL_REJECTED UINT64_C(0x0201)
#define LEANOS_COMPOSITE_STATE_MALFORMED_MAP_REJECTED UINT64_C(0x0301)
#define LEANOS_COMPOSITE_STATE_SCHEDULER_OBSERVED UINT64_C(0x0401)
#define LEANOS_COMPOSITE_STATE_SUBJECT_TERMINATED UINT64_C(0x0501)
#define LEANOS_COMPOSITE_STATE_FATAL_ENTERED UINT64_C(0x0601)
#define LEANOS_COMPOSITE_STATE_POST_FATAL_REJECTED UINT64_C(0x0701)

#define LEANOS_COMPOSITE_STATE_MIXED_INITIAL UINT64_C(0x0801)
#define LEANOS_COMPOSITE_STATE_TRANSFER_OFFERED UINT64_C(0x0901)
#define LEANOS_COMPOSITE_STATE_TRANSFER_ACCEPTED UINT64_C(0x0a01)
#define LEANOS_COMPOSITE_STATE_TRANSFER_REVOKED UINT64_C(0x0b01)
#define LEANOS_COMPOSITE_STATE_STALE_HANDLE_REJECTED UINT64_C(0x0c01)
#define LEANOS_COMPOSITE_STATE_FRESH_CAPABILITY_COPIED UINT64_C(0x0d01)
#define LEANOS_COMPOSITE_STATE_SYSCALL_MAPPED UINT64_C(0x0e01)
#define LEANOS_COMPOSITE_STATE_DIRECT_MAPPED UINT64_C(0x0f01)
#define LEANOS_COMPOSITE_STATE_MIXED_UNKNOWN_SYSCALL_REJECTED UINT64_C(0x1001)
#define LEANOS_COMPOSITE_STATE_NONBLOCKING_SENT UINT64_C(0x1101)
#define LEANOS_COMPOSITE_STATE_NONBLOCKING_RECEIVED UINT64_C(0x1201)
#define LEANOS_COMPOSITE_STATE_BLOCKING_RECEIVER_BLOCKED UINT64_C(0x1301)
#define LEANOS_COMPOSITE_STATE_BLOCKING_RECEIVER_WOKEN UINT64_C(0x1401)
#define LEANOS_COMPOSITE_STATE_TIMER_SWITCHED UINT64_C(0x1501)
#define LEANOS_COMPOSITE_STATE_USER_FAULT_CLEANED UINT64_C(0x1601)
#define LEANOS_COMPOSITE_STATE_MIXED_FATAL_ENTERED UINT64_C(0x1701)
#define LEANOS_COMPOSITE_STATE_MIXED_POST_FATAL_REJECTED UINT64_C(0x1801)

#define LEANOS_COMPOSITE_COMMAND_CREATE_SUBJECT_ONE UINT64_C(0x0101)
#define LEANOS_COMPOSITE_COMMAND_REJECT_UNKNOWN_SYSCALL UINT64_C(0x0201)
#define LEANOS_COMPOSITE_COMMAND_REJECT_MALFORMED_MAP UINT64_C(0x0301)
#define LEANOS_COMPOSITE_COMMAND_OBSERVE_SCHEDULER UINT64_C(0x0401)
#define LEANOS_COMPOSITE_COMMAND_TERMINATE_SUBJECT_ONE UINT64_C(0x0501)
#define LEANOS_COMPOSITE_COMMAND_ENTER_FATAL_KERNEL_FAULT UINT64_C(0x0601)
#define LEANOS_COMPOSITE_COMMAND_ATTEMPT_POST_FATAL_SCHEDULE UINT64_C(0x0701)
#define LEANOS_COMPOSITE_COMMAND_REJECT_STALE_MAP_HANDLE UINT64_C(0x0801)
#define LEANOS_COMPOSITE_COMMAND_REJECT_NONBLOCKING_RECEIVE UINT64_C(0x0901)
#define LEANOS_COMPOSITE_COMMAND_REJECT_CAPABILITY_COPY UINT64_C(0x0a01)
#define LEANOS_COMPOSITE_COMMAND_REJECT_BLOCKING_CANCEL UINT64_C(0x0b01)
#define LEANOS_COMPOSITE_COMMAND_REJECT_DEFERRED_DRAIN UINT64_C(0x0c01)

#define LEANOS_COMPOSITE_COMMAND_TRANSFER_OFFER UINT64_C(0x2001)
#define LEANOS_COMPOSITE_COMMAND_TRANSFER_ACCEPT UINT64_C(0x2101)
#define LEANOS_COMPOSITE_COMMAND_REVOKE_TRANSFERRED UINT64_C(0x2201)
#define LEANOS_COMPOSITE_COMMAND_REJECT_STALE_REUSED_HANDLE UINT64_C(0x2301)
#define LEANOS_COMPOSITE_COMMAND_COPY_FRESH_CAPABILITY UINT64_C(0x2401)
#define LEANOS_COMPOSITE_COMMAND_ACCEPTED_SYSCALL_MAP UINT64_C(0x2501)
#define LEANOS_COMPOSITE_COMMAND_ACCEPTED_DIRECT_MAP UINT64_C(0x2601)
#define LEANOS_COMPOSITE_COMMAND_REJECT_MIXED_UNKNOWN_SYSCALL UINT64_C(0x2701)
#define LEANOS_COMPOSITE_COMMAND_NONBLOCKING_SEND UINT64_C(0x2801)
#define LEANOS_COMPOSITE_COMMAND_NONBLOCKING_RECEIVE UINT64_C(0x2901)
#define LEANOS_COMPOSITE_COMMAND_BLOCKING_RECEIVE UINT64_C(0x2a01)
#define LEANOS_COMPOSITE_COMMAND_BLOCKING_SEND UINT64_C(0x2b01)
#define LEANOS_COMPOSITE_COMMAND_TIMER_SWITCH UINT64_C(0x2c01)
#define LEANOS_COMPOSITE_COMMAND_USER_FAULT_CLEANUP UINT64_C(0x2d01)
#define LEANOS_COMPOSITE_COMMAND_ENTER_MIXED_FATAL UINT64_C(0x2e01)
#define LEANOS_COMPOSITE_COMMAND_ATTEMPT_MIXED_POST_FATAL UINT64_C(0x2f01)

#define LEANOS_COMPOSITE_ERROR_WRONG_VERSION UINT64_C(0xff01)
#define LEANOS_COMPOSITE_ERROR_RESERVED_BITS UINT64_C(0xff02)
#define LEANOS_COMPOSITE_ERROR_UNKNOWN_STATE UINT64_C(0xff03)
#define LEANOS_COMPOSITE_ERROR_UNKNOWN_COMMAND UINT64_C(0xff04)
#define LEANOS_COMPOSITE_ERROR_NONCANONICAL_ARGUMENTS UINT64_C(0xff05)
#define LEANOS_COMPOSITE_ERROR_INVALID_SEQUENCE UINT64_C(0xff06)

uint64_t leanos_composite_dispatch(
    uint64_t state,
    uint64_t command,
    uint64_t arg0,
    uint64_t arg1,
    uint64_t arg2,
    uint64_t arg3);

/*
 * Allocation-free generated validation of the exact canonical q35 DMA
 * snapshot. Each manifest slot supplies identity and control words in the
 * compact format documented by LeanOS.CompositeDispatcher.
 */
uint64_t leanos_validate_q35_dma_snapshot(
    uint64_t version,
    uint64_t topology,
    uint64_t identity0,
    uint64_t control0,
    uint64_t identity1,
    uint64_t control1,
    uint64_t identity2,
    uint64_t control2,
    uint64_t identity3,
    uint64_t control3,
    uint64_t identity4,
    uint64_t control4,
    uint64_t identity5,
    uint64_t control5);

#endif
